/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CallId = IDL.Text;
export const Timestamp = IDL.Int;
export const CallStatus = IDL.Variant({
  'ringing' : IDL.Null,
  'initiated' : IDL.Null,
  'missed' : IDL.Null,
  'ended' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const CallKind = IDL.Variant({ 'video' : IDL.Null, 'voice' : IDL.Null });
export const UserId = IDL.Principal;
export const CallSession = IDL.Record({
  'id' : CallId,
  'startTime' : Timestamp,
  'status' : CallStatus,
  'offer' : IDL.Opt(IDL.Text),
  'endTime' : IDL.Opt(Timestamp),
  'kind' : CallKind,
  'answer' : IDL.Opt(IDL.Text),
  'isActive' : IDL.Bool,
  'callee' : UserId,
  'caller' : UserId,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ConversationId = IDL.Text;
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Message = IDL.Record({
  'id' : IDL.Nat,
  'text' : IDL.Text,
  'sender' : UserId,
  'timestamp' : Timestamp,
  'image' : IDL.Opt(ExternalBlob),
});
export const ConversationMetadata = IDL.Record({
  'participants' : IDL.Tuple(UserId, UserId),
  'lastMessage' : IDL.Opt(Message),
  'lastUpdate' : Timestamp,
  'conversationId' : IDL.Text,
});
export const InternalUserProfile = IDL.Record({
  'principal' : IDL.Principal,
  'displayName' : IDL.Text,
});
export const FriendshipStatus = IDL.Variant({
  'blocked' : IDL.Null,
  'pendingOutgoing' : IDL.Null,
  'notFriends' : IDL.Null,
  'friends' : IDL.Null,
  'pendingIncoming' : IDL.Null,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'answerCall' : IDL.Func([CallId, IDL.Text], [CallSession], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'checkHealth' : IDL.Func(
      [],
      [IDL.Record({ 'status' : IDL.Text })],
      ['query'],
    ),
  'declineFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'deleteConversation' : IDL.Func([ConversationId], [], []),
  'getCallSession' : IDL.Func([CallId], [IDL.Opt(CallSession)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(ConversationMetadata)], ['query']),
  'getCurrentUser' : IDL.Func([], [IDL.Opt(InternalUserProfile)], ['query']),
  'getFriendCommand' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
  'getFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
  'getPendingFriendRequests' : IDL.Func(
      [],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getPendingIncomingCalls' : IDL.Func([], [IDL.Vec(CallSession)], ['query']),
  'getRelationshipStatus' : IDL.Func(
      [IDL.Principal],
      [FriendshipStatus],
      ['query'],
    ),
  'getUnreadConversations' : IDL.Func([], [IDL.Vec(ConversationId)], ['query']),
  'getUser' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(InternalUserProfile)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'markAsRead' : IDL.Func([ConversationId], [], []),
  'register' : IDL.Func([IDL.Text], [InternalUserProfile], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsers' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(InternalUserProfile)],
      ['query'],
    ),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'sendMessage' : IDL.Func(
      [ConversationId, IDL.Text, IDL.Opt(ExternalBlob)],
      [Message],
      [],
    ),
  'startCall' : IDL.Func([UserId, CallKind, IDL.Text], [CallSession], []),
  'startConversation' : IDL.Func([UserId], [ConversationId], []),
  'updateCallStatus' : IDL.Func([CallId, CallStatus], [CallSession], []),
  'updateDisplayName' : IDL.Func([IDL.Text], [InternalUserProfile], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CallId = IDL.Text;
  const Timestamp = IDL.Int;
  const CallStatus = IDL.Variant({
    'ringing' : IDL.Null,
    'initiated' : IDL.Null,
    'missed' : IDL.Null,
    'ended' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const CallKind = IDL.Variant({ 'video' : IDL.Null, 'voice' : IDL.Null });
  const UserId = IDL.Principal;
  const CallSession = IDL.Record({
    'id' : CallId,
    'startTime' : Timestamp,
    'status' : CallStatus,
    'offer' : IDL.Opt(IDL.Text),
    'endTime' : IDL.Opt(Timestamp),
    'kind' : CallKind,
    'answer' : IDL.Opt(IDL.Text),
    'isActive' : IDL.Bool,
    'callee' : UserId,
    'caller' : UserId,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ConversationId = IDL.Text;
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Message = IDL.Record({
    'id' : IDL.Nat,
    'text' : IDL.Text,
    'sender' : UserId,
    'timestamp' : Timestamp,
    'image' : IDL.Opt(ExternalBlob),
  });
  const ConversationMetadata = IDL.Record({
    'participants' : IDL.Tuple(UserId, UserId),
    'lastMessage' : IDL.Opt(Message),
    'lastUpdate' : Timestamp,
    'conversationId' : IDL.Text,
  });
  const InternalUserProfile = IDL.Record({
    'principal' : IDL.Principal,
    'displayName' : IDL.Text,
  });
  const FriendshipStatus = IDL.Variant({
    'blocked' : IDL.Null,
    'pendingOutgoing' : IDL.Null,
    'notFriends' : IDL.Null,
    'friends' : IDL.Null,
    'pendingIncoming' : IDL.Null,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'acceptFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'answerCall' : IDL.Func([CallId, IDL.Text], [CallSession], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'checkHealth' : IDL.Func(
        [],
        [IDL.Record({ 'status' : IDL.Text })],
        ['query'],
      ),
    'declineFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'deleteConversation' : IDL.Func([ConversationId], [], []),
    'getCallSession' : IDL.Func([CallId], [IDL.Opt(CallSession)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationMetadata)],
        ['query'],
      ),
    'getCurrentUser' : IDL.Func([], [IDL.Opt(InternalUserProfile)], ['query']),
    'getFriendCommand' : IDL.Func([IDL.Principal], [IDL.Text], ['query']),
    'getFriends' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getMessages' : IDL.Func([ConversationId], [IDL.Vec(Message)], ['query']),
    'getPendingFriendRequests' : IDL.Func(
        [],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getPendingIncomingCalls' : IDL.Func([], [IDL.Vec(CallSession)], ['query']),
    'getRelationshipStatus' : IDL.Func(
        [IDL.Principal],
        [FriendshipStatus],
        ['query'],
      ),
    'getUnreadConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationId)],
        ['query'],
      ),
    'getUser' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(InternalUserProfile)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'markAsRead' : IDL.Func([ConversationId], [], []),
    'register' : IDL.Func([IDL.Text], [InternalUserProfile], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsers' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(InternalUserProfile)],
        ['query'],
      ),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'sendMessage' : IDL.Func(
        [ConversationId, IDL.Text, IDL.Opt(ExternalBlob)],
        [Message],
        [],
      ),
    'startCall' : IDL.Func([UserId, CallKind, IDL.Text], [CallSession], []),
    'startConversation' : IDL.Func([UserId], [ConversationId], []),
    'updateCallStatus' : IDL.Func([CallId, CallStatus], [CallSession], []),
    'updateDisplayName' : IDL.Func([IDL.Text], [InternalUserProfile], []),
  });
};

export const init = ({ IDL }) => { return []; };