/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type ConversationId = string;
export interface ConversationMetadata {
  'participants' : [UserId, UserId],
  'lastMessage' : [] | [Message],
  'lastUpdate' : Timestamp,
}
export type ExternalBlob = Uint8Array;
export interface InternalUserProfile {
  'principal' : Principal,
  'displayName' : string,
}
export interface Message {
  'id' : bigint,
  'text' : string,
  'sender' : UserId,
  'timestamp' : Timestamp,
  'image' : [] | [ExternalBlob],
}
export type Timestamp = bigint;
export type UserId = Principal;
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteConversation' : ActorMethod<[ConversationId], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getConversations' : ActorMethod<[], Array<ConversationMetadata>>,
  'getCurrentUser' : ActorMethod<[], [] | [InternalUserProfile]>,
  'getMessages' : ActorMethod<[ConversationId], Array<Message>>,
  'getUnreadConversations' : ActorMethod<[], Array<ConversationId>>,
  'getUser' : ActorMethod<[Principal], [] | [InternalUserProfile]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'markAsRead' : ActorMethod<[ConversationId], undefined>,
  'register' : ActorMethod<[string], InternalUserProfile>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsers' : ActorMethod<[string], Array<InternalUserProfile>>,
  'sendMessage' : ActorMethod<
    [ConversationId, string, [] | [ExternalBlob]],
    Message
  >,
  'startConversation' : ActorMethod<[UserId], ConversationId>,
  'updateDisplayName' : ActorMethod<[string], InternalUserProfile>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];